kind: Simple
apiVersion: k3d.io/v1alpha2
name: argocd-image-updater-demo
image: rancher/k3s:v1.20.4-k3s1
ports:
- port: 80:80
  nodeFilters:
  - loadbalancer
- port: 443:443
  nodeFilters:
  - loadbalancer
